server:
  port: 8762
spring:
  application:
   name: eureka-server-7002

eureka:
  instance:
    hostname: eureka7002.com
  prefer-ip-address: true

  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7001.com:8761/eureka/    #集群模式:相互注册
      #defaultZone: http://eureka7002.com:8762/eureka/    #单机模式

  server:
    enable-self-preservation: false  #关闭自我保护机制，可以及时踢掉不可用服务
    eviction-interval-timer-in-ms: 2000
